### ISSUE TITLE
[Bug] Access error

### ISSUE THREAD

**Issue by Drakemoor** [reply2za/obsidian-query-control#3]
As of yesterday I began to see this error in the console. 
```markdown
Access to fetch at 'https://github.com/reply2za/obsidian-query-control/' from origin 'app://obsidian.md' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
github.com/reply2za/obsidian-query-control/:1 
       Failed to load resource: net::ERR_FAILED
```

I have no idea what does it mean or if something should be done about it, but I thought I should report it.  

I also have no idea how to replicate it. If I find out I would report here. 

Thanks

**Comment by reply2za** [comment]
The plugin doesn't do any fetch operation. This likely BRAT checking the repo for updates and in doing so it might've encountered some network error. I wouldn't worry about it unless you're repeatedly seeing it every time you launch the app.
