### ISSUE TITLE
main.js missing?

### ISSUE THREAD

**Issue by creadian** [reply2za/obsidian-query-control#6]
Hi, sorry I'm not a coder so I don't know if I'm talking crap, but can it be that main.js is missing?
I wasn't able to add it via BRAT, only using the 'frozen version' way. The plugin doesn't work for me though, so I thought maybe it's due to a missing main.js.
Thanks for maintaining this plugin!

**Comment by creadian** [comment]
UPDATE: it started working after I activated and opened the backlinks core plugin!

**Comment by TfTHacker** [comment]
The manifest version is pointing to a release that does not exist.

**Comment by reply2za** [comment]
@TfTHacker The manifest attached to the latest release is pointing to the same release number. Could the issue be that it is looking for the same version in `master` as well?

**Comment by reply2za** [comment]
Using "add frozen version" with `0.7.12` works?

**Comment by TfTHacker** [comment]
> @TfTHacker The manifest attached to the latest release is pointing to the same release number. Could the issue be that it is looking for the same version in `master` as well?

Obsidian uses the manifest.json in the root of your repo to determine the current release version of the plugin, then downloads that release, including style.css, main.js and manifest.json.

So regarding download, manifest.json in the root is what is important.

**Comment by creadian** [comment]
> Using "add frozen version" with `0.7.12` works?

Inwas only able to add it with brat using 'frozen' 0.7.12.
The plugin only "got active" after opening it in the sidebar backlinks view.

**Comment by reply2za** [comment]
Ah ok. Thanks for the clarification. 

This should be resolved now so I'll be closing this report. Thanks!
