### ISSUE TITLE
Installed, but when I go to enable, says "Failed to Load"

### ISSUE THREAD

**Issue by ashcreighton** [reply2za/obsidian-query-control#7]
Have I installed it incorrectly?

I've tried installing manually (taking the main.js and manifest.json files, but having to change main.ts extension to .js first. i also tried leaving it main.ts; neither worked.)

I tried installing via BRAT. Didn't work.

Tried installing this while original Query Control was still installed; tried again after *uninstalling* original Query Control.

Nothing is working and I can't think of anything else to try...

**Comment by ashcreighton** [comment]
Apologies—I was not downloading from the **Releases** page. It is working now.

**Comment by agilemofo** [comment]
I'm getting this issue when trying to install via BRAT. It's still registering 0.6.0 and then apparently breaking my ability to load obsidian preferences it all. I have to quit the app and reload, and while the plugin shows up in my community plugins list, it cannot load.

Is there a new repo we have to specify in the BRAT plugin?
